Repository DO-SOPT-CDS-5/EQL-Client, pull requests merged in 2023-12, with the labels that each got.

#53 [Fix/#52] orderview item page & build 에러 잡기
  EQL-Client-Project/src/App.tsx
  EQL-Client-Project/src/Router.tsx
  EQL-Client-Project/src/components/Category/CategoryItemDetail/CategoryItemDetail.tsx
  EQL-Client-Project/src/components/Category/CategoryProductList/CategoryProductList.style.tsx
  EQL-Client-Project/src/components/header/Header.tsx
  EQL-Client-Project/src/components/home/Content/ContentWrapper/ContentWrapper.tsx
  EQL-Client-Project/src/components/home/Section/SectionContainer/SectionContainer.tsx
  EQL-Client-Project/src/components/home/Section/SectionLayout/SectionLayout.tsx
  EQL-Client-Project/src/components/home/Section/SectionWrapper/SectionWrapper.tsx
  EQL-Client-Project/src/components/order/DeliveryInfo/DeliveryInfo.tsx
  EQL-Client-Project/src/components/order/OrderProductInfo/OrderProductInfo.style.tsx
  EQL-Client-Project/src/components/order/OrderProductInfo/OrderProductInfo.tsx
  EQL-Client-Project/src/constants/ProductImgs.ts
  EQL-Client-Project/src/pages/Home/Home.tsx
  EQL-Client-Project/src/pages/Order/Order.tsx
  EQL-Client-Project/src/pages/Product/Left.tsx
Labels: 재훈, build

#57 [Feat/#49]home view api
  EQL-Client-Project/src/assets/Images/ImgPost6.png
  EQL-Client-Project/src/assets/images/0_images.ts
  EQL-Client-Project/src/assets/images/CarouselFirstImg.png
  EQL-Client-Project/src/assets/images/CarouselSecondImg.png
  EQL-Client-Project/src/assets/images/CarouselThirdImg.png
  EQL-Client-Project/src/assets/images/ImgPost1.png
  EQL-Client-Project/src/assets/images/ImgPost10.png
  EQL-Client-Project/src/assets/images/ImgPost2.png
  EQL-Client-Project/src/assets/images/ImgPost3.png
  EQL-Client-Project/src/assets/images/ImgPost4.png
  EQL-Client-Project/src/assets/images/ImgPost5.png
  EQL-Client-Project/src/assets/images/ImgPost6.png
  EQL-Client-Project/src/assets/images/ImgPost7.png
  EQL-Client-Project/src/assets/images/ImgPost8.png
  EQL-Client-Project/src/assets/images/ImgPost9.png
  EQL-Client-Project/src/assets/images/ImgProduct1.png
  EQL-Client-Project/src/assets/images/ImgProduct10.png
  EQL-Client-Project/src/assets/images/ImgProduct11.png
  EQL-Client-Project/src/assets/images/ImgProduct12.png
  EQL-Client-Project/src/assets/images/ImgProduct13.png
  EQL-Client-Project/src/assets/images/ImgProduct14.png
  EQL-Client-Project/src/assets/images/ImgProduct15.png
  EQL-Client-Project/src/assets/images/ImgProduct16.png
  EQL-Client-Project/src/assets/images/ImgProduct17.png
  EQL-Client-Project/src/assets/images/ImgProduct18.png
  EQL-Client-Project/src/assets/images/ImgProduct19.png
  EQL-Client-Project/src/assets/images/ImgProduct2.png
  EQL-Client-Project/src/assets/images/ImgProduct20.png
  EQL-Client-Project/src/assets/images/ImgProduct21.png
  EQL-Client-Project/src/assets/images/ImgProduct22.png
  EQL-Client-Project/src/assets/images/ImgProduct23.png
  EQL-Client-Project/src/assets/images/ImgProduct24.png
  EQL-Client-Project/src/assets/images/ImgProduct25.png
  EQL-Client-Project/src/assets/images/ImgProduct26.png
  EQL-Client-Project/src/assets/images/ImgProduct27.png
  EQL-Client-Project/src/assets/images/ImgProduct28.png
  EQL-Client-Project/src/assets/images/ImgProduct29.png
  EQL-Client-Project/src/assets/images/ImgProduct3.png
  EQL-Client-Project/src/assets/images/ImgProduct30.png
  EQL-Client-Project/src/assets/images/ImgProduct4.png
  EQL-Client-Project/src/assets/images/ImgProduct5.png
  EQL-Client-Project/src/assets/images/ImgProduct6.png
  EQL-Client-Project/src/assets/images/ImgProduct7.png
  EQL-Client-Project/src/assets/images/ImgProduct8.png
  EQL-Client-Project/src/assets/images/ImgProduct9.png
  EQL-Client-Project/src/assets/images/ImgRec1.png
  EQL-Client-Project/src/assets/images/ImgRec2.png
  EQL-Client-Project/src/assets/images/ImgRec3.png
  EQL-Client-Project/src/assets/images/ImgRec4.png
  EQL-Client-Project/src/assets/images/ImgRec5.png
  EQL-Client-Project/src/assets/images/ImgRec6.png
  EQL-Client-Project/src/assets/images/ImgRec7.png
  EQL-Client-Project/src/assets/images/RecommendFirstImg.png
  EQL-Client-Project/src/assets/images/RecommendSecondImg.png
  EQL-Client-Project/src/assets/images/index.ts
  EQL-Client-Project/src/assets/svgs/0_icons.ts
  EQL-Client-Project/src/components/header/Header.tsx
  EQL-Client-Project/src/components/home/Content/ContentWrapper/ContentWrapper.tsx
  EQL-Client-Project/src/pages/Home/Home.style.tsx
  EQL-Client-Project/src/pages/Home/Home.tsx
Labels: 준민, API

#66 feat/#58: Product 자잘한 수정]
  EQL-Client-Project/src/assets/Images/index.ts
  EQL-Client-Project/src/assets/images/index.ts
  EQL-Client-Project/src/components/Product/Left.style.tsx
  EQL-Client-Project/src/components/Product/Left.tsx
  EQL-Client-Project/src/components/Product/Right.style.tsx
  EQL-Client-Project/src/components/Product/Right.tsx
  EQL-Client-Project/src/components/home/Content/ContentWrapper/ContentWrapper.tsx
  EQL-Client-Project/src/pages/Home/Home.style.tsx
  EQL-Client-Project/src/pages/Home/Home.tsx
  EQL-Client-Project/src/pages/Product/Product.tsx
Labels: feat, 시연, Product
