Repository DO-SOPT-CDS-5/EQL-Client, pull requests merged in 2023-11, with the labels that each got.

#3 [Init] svg 초기세팅
  EQL-Client-Project/package.json
  EQL-Client-Project/src/App.tsx
  EQL-Client-Project/src/icons/0_icons.js
  EQL-Client-Project/src/icons/IcArrow.svg
  EQL-Client-Project/src/icons/IcArrowBlackLeft.svg
  EQL-Client-Project/src/icons/IcArrowDown.svg
  EQL-Client-Project/src/icons/IcArrowDropdown.svg
  EQL-Client-Project/src/icons/IcArrowGrayLeft.svg
  EQL-Client-Project/src/icons/IcArrowGrayRight.svg
  EQL-Client-Project/src/icons/IcArrowRight.svg
  EQL-Client-Project/src/icons/IcArrowUp.svg
  EQL-Client-Project/src/icons/IcBookmarkActive.svg
  EQL-Client-Project/src/icons/IcBookmarkDefault.svg
  EQL-Client-Project/src/icons/IcChat.svg
  EQL-Client-Project/src/icons/IcCheck.svg
  EQL-Client-Project/src/icons/IcCheckboxPayment.svg
  EQL-Client-Project/src/icons/IcCheckboxPaymentChecked.svg
  EQL-Client-Project/src/icons/IcJoin.svg
  EQL-Client-Project/src/icons/IcLogin.svg
  EQL-Client-Project/src/icons/IcMinus.svg
  EQL-Client-Project/src/icons/IcMypage.svg
  EQL-Client-Project/src/icons/IcOption.svg
  EQL-Client-Project/src/icons/IcPlus.svg
  EQL-Client-Project/src/icons/IcSearch.svg
  EQL-Client-Project/src/icons/IcSmallstarGray.svg
  EQL-Client-Project/src/icons/IcSmallstarRed.svg
  EQL-Client-Project/src/icons/IcUndo.svg
  EQL-Client-Project/src/vite-env.d.ts
  EQL-Client-Project/tsconfig.json
  EQL-Client-Project/vite.config.ts
  EQL-Client-Project/yarn.lock
Labels: 수연, 초기세팅

#4 [init] Theme(fonts)
  EQL-Client-Project/src/pages/Home/Home.tsx
  EQL-Client-Project/src/styles/theme.ts
Labels: 준민, 초기세팅

#8 [Feat/#7] svg setting change
  EQL-Client-Project/.eslintrc.json
  EQL-Client-Project/src/App.tsx
  EQL-Client-Project/src/assets/svgs/0_icons.ts
  EQL-Client-Project/src/assets/svgs/IcArrow.svg
  EQL-Client-Project/src/assets/svgs/IcArrowBlackLeft.svg
  EQL-Client-Project/src/assets/svgs/IcArrowDown.svg
  EQL-Client-Project/src/assets/svgs/IcArrowDropdown.svg
  EQL-Client-Project/src/assets/svgs/IcArrowGrayLeft.svg
  EQL-Client-Project/src/assets/svgs/IcArrowGrayRight.svg
  EQL-Client-Project/src/assets/svgs/IcArrowRight.svg
  EQL-Client-Project/src/assets/svgs/IcArrowUp.svg
  EQL-Client-Project/src/assets/svgs/IcBookmarkActive.svg
  EQL-Client-Project/src/assets/svgs/IcBookmarkDefault.svg
  EQL-Client-Project/src/assets/svgs/IcChat.svg
  EQL-Client-Project/src/assets/svgs/IcCheck.svg
  EQL-Client-Project/src/assets/svgs/IcCheckboxPayment.svg
  EQL-Client-Project/src/assets/svgs/IcCheckboxPaymentChecked.svg
  EQL-Client-Project/src/assets/svgs/IcJoin.svg
  EQL-Client-Project/src/assets/svgs/IcLogin.svg
  EQL-Client-Project/src/assets/svgs/IcMinus.svg
  EQL-Client-Project/src/assets/svgs/IcMypage.svg
  EQL-Client-Project/src/assets/svgs/IcOption.svg
  EQL-Client-Project/src/assets/svgs/IcPlus.svg
  EQL-Client-Project/src/assets/svgs/IcSearch.svg
  EQL-Client-Project/src/assets/svgs/IcSmallstarGray.svg
  EQL-Client-Project/src/assets/svgs/IcSmallstarRed.svg
  EQL-Client-Project/src/assets/svgs/IcUndo.svg
  EQL-Client-Project/src/styles/globalStyle.ts
  EQL-Client-Project/src/svg.d.ts
  EQL-Client-Project/tsconfig.json
Labels: fix, 재훈

#12 [Feat/#6] layout component + eslint import order
  EQL-Client-Project/.eslintrc.json
  EQL-Client-Project/src/App.tsx
  EQL-Client-Project/src/components/common/LayoutComponent.tsx
  EQL-Client-Project/src/components/footer/Footer.style.tsx
  EQL-Client-Project/src/components/footer/Footer.tsx
  EQL-Client-Project/src/components/header/Header.tsx
  EQL-Client-Project/src/pages/Home/Home.tsx
Labels: feat, 재훈

#17 [Feat/#15] Footer & theme 속성 추가
  EQL-Client-Project/index.html
  EQL-Client-Project/src/assets/svgs/IcFavicon.svg
  EQL-Client-Project/src/components/footer/Footer.style.tsx
  EQL-Client-Project/src/components/footer/Footer.tsx
  EQL-Client-Project/src/styles/theme.ts
Labels: feat, 재훈

#21 [hotfix/#20] theme transparent 색상 변경
  EQL-Client-Project/src/styles/stlye.d.ts
  EQL-Client-Project/src/styles/theme.ts
Labels: hotfix, theme

#27 Feat/#26/order bread crumb
  EQL-Client-Project/src/Router.tsx
  EQL-Client-Project/src/assets/svgs/0_icons.ts
  EQL-Client-Project/src/assets/svgs/IcOrderArrowRight.svg
  EQL-Client-Project/src/components/footer/Footer.tsx
  EQL-Client-Project/src/components/order/BreadCrumb/BreadCrumb.style.tsx
  EQL-Client-Project/src/components/order/BreadCrumb/BreadCrumb.tsx
  EQL-Client-Project/src/components/order/BreadCrumb/BreadCrumbItem/BreadCrumbItem.style.tsx
  EQL-Client-Project/src/components/order/BreadCrumb/BreadCrumbItem/BreadCrumbItem.tsx
  EQL-Client-Project/src/constants/BreadCrumbs.ts
  EQL-Client-Project/src/pages/Order/Order.tsx
  EQL-Client-Project/src/utils/comparePath.ts
Labels: feat, 재훈

#28 [Feat/#13] category basic view
  .DS_Store
  EQL-Client-Project/package.json
  EQL-Client-Project/src/components/Category/CategoryItemDetail/CategoryItemDatail.style.tsx
  EQL-Client-Project/src/components/Category/CategoryItemDetail/CategoryItemDetail.tsx
  EQL-Client-Project/src/components/Category/CategoryMainContent/CategoryMainContent.style.tsx
  EQL-Client-Project/src/components/Category/CategoryMainContent/CategoryMainContent.tsx
  EQL-Client-Project/src/components/Category/CategoryNav/CategoryNav.style.tsx
  EQL-Client-Project/src/components/Category/CategoryNav/CategoryNav.tsx
  EQL-Client-Project/src/components/Category/CategoryNavLink/CategoryNavLink.style.tsx
  EQL-Client-Project/src/components/Category/CategoryNavLink/CategoryNavLink.tsx
  EQL-Client-Project/src/constants/categoryDetails.ts
  EQL-Client-Project/src/pages/Category/Category.style.tsx
  EQL-Client-Project/src/pages/Category/Category.tsx
  EQL-Client-Project/src/styles/theme.ts
Labels: feat, 수연

#34 Feat/#13/category basic view
  EQL-Client-Project/src/assets/Images/0_images.ts
  EQL-Client-Project/src/assets/Images/ImgProduct1.png
  EQL-Client-Project/src/assets/Images/ImgProduct10.png
  EQL-Client-Project/src/assets/Images/ImgProduct11.png
  EQL-Client-Project/src/assets/Images/ImgProduct12.png
  EQL-Client-Project/src/assets/Images/ImgProduct13.png
  EQL-Client-Project/src/assets/Images/ImgProduct14.png
  EQL-Client-Project/src/assets/Images/ImgProduct15.png
  EQL-Client-Project/src/assets/Images/ImgProduct16.png
  EQL-Client-Project/src/assets/Images/ImgProduct17.png
  EQL-Client-Project/src/assets/Images/ImgProduct18.png
  EQL-Client-Project/src/assets/Images/ImgProduct19.png
  EQL-Client-Project/src/assets/Images/ImgProduct2.png
  EQL-Client-Project/src/assets/Images/ImgProduct20.png
  EQL-Client-Project/src/assets/Images/ImgProduct21.png
  EQL-Client-Project/src/assets/Images/ImgProduct22.png
  EQL-Client-Project/src/assets/Images/ImgProduct23.png
  EQL-Client-Project/src/assets/Images/ImgProduct24.png
  EQL-Client-Project/src/assets/Images/ImgProduct25.png
  EQL-Client-Project/src/assets/Images/ImgProduct26.png
  EQL-Client-Project/src/assets/Images/ImgProduct27.png
  EQL-Client-Project/src/assets/Images/ImgProduct28.png
  EQL-Client-Project/src/assets/Images/ImgProduct29.png
  EQL-Client-Project/src/assets/Images/ImgProduct3.png
  EQL-Client-Project/src/assets/Images/ImgProduct30.png
  EQL-Client-Project/src/assets/Images/ImgProduct4.png
  EQL-Client-Project/src/assets/Images/ImgProduct5.png
  EQL-Client-Project/src/assets/Images/ImgProduct6.png
  EQL-Client-Project/src/assets/Images/ImgProduct7.png
  EQL-Client-Project/src/assets/Images/ImgProduct8.png
  EQL-Client-Project/src/assets/Images/ImgProduct9.png
  EQL-Client-Project/src/constants/ProductImgs.ts
Labels: feat, 수연

#36 Feat/#31/category main content
  EQL-Client-Project/src/assets/svgs/0_icons.ts
  EQL-Client-Project/src/assets/svgs/IcNew.svg
  EQL-Client-Project/src/components/Category/CategoryFilter/CategoryFilter.style.tsx
  EQL-Client-Project/src/components/Category/CategoryFilter/CategoryFilter.tsx
  EQL-Client-Project/src/components/Category/CategoryFilterBtn/CategoryFilterBtn.style.tsx
  EQL-Client-Project/src/components/Category/CategoryFilterBtn/CategoryFilterBtn.tsx
  EQL-Client-Project/src/components/Category/CategoryItemDetail/CategoryItemDatail.style.tsx
  EQL-Client-Project/src/components/Category/CategoryItemDetail/CategoryItemDetail.tsx
  EQL-Client-Project/src/components/Category/CategoryMainContent/CategoryMainContent.style.tsx
  EQL-Client-Project/src/components/Category/CategoryMainContent/CategoryMainContent.tsx
  EQL-Client-Project/src/components/Category/CategoryNav/CategoryNav.style.tsx
  EQL-Client-Project/src/components/Category/CategoryProductList/CategoryProductList.style.tsx
  EQL-Client-Project/src/components/Category/CategoryProductList/CategoryProductList.tsx
  EQL-Client-Project/src/constants/ProductImgs.ts
  EQL-Client-Project/src/pages/Category/Category.style.tsx
  EQL-Client-Project/src/pages/Category/Category.tsx
Labels: feat, 수연

#35 [Feat/#33] top btn 구현
  EQL-Client-Project/src/assets/svgs/0_icons.ts
  EQL-Client-Project/src/assets/svgs/IcArrowUpLinear.svg
  EQL-Client-Project/src/components/common/LayoutComponent.tsx
  EQL-Client-Project/src/components/topButton/TopBtn.style.tsx
  EQL-Client-Project/src/components/topButton/TopBtn.tsx
Labels: feat, 시연

#40 [Feat/#38] api 기본 세팅 - axios instance 생성
  EQL-Client-Project/.gitignore
  EQL-Client-Project/package.json
  EQL-Client-Project/src/utils/api/axios.ts
  EQL-Client-Project/yarn.lock
Labels: feat, 시연, API

#37 [Feat/#19] header view
  EQL-Client-Project/src/assets/svgs/0_icons.ts
  EQL-Client-Project/src/assets/svgs/IcCart.svg
  EQL-Client-Project/src/assets/svgs/IcEqlLogo.svg
  EQL-Client-Project/src/assets/svgs/IcLine.svg
  EQL-Client-Project/src/components/header/Header.style.tsx
  EQL-Client-Project/src/components/header/Header.tsx
  EQL-Client-Project/src/components/header/dropdown/DropDown.style.tsx
  EQL-Client-Project/src/components/header/dropdown/DropDown.tsx
  EQL-Client-Project/src/pages/Home/Home.style.tsx
  EQL-Client-Project/src/pages/Home/Home.tsx
  EQL-Client-Project/src/styles/theme.ts
Labels: feat, 준민

#41 [Feat/#32] order view
  EQL-Client-Project/src/assets/svgs/0_icons.ts
  EQL-Client-Project/src/assets/svgs/IcOrderCheck.svg
  EQL-Client-Project/src/assets/svgs/IcOrderCheckboxPayment.svg
  EQL-Client-Project/src/assets/svgs/IcOrderCheckboxPaymentChecked.svg
  EQL-Client-Project/src/assets/svgs/IcOrderEventTag.svg
  EQL-Client-Project/src/components/common/spacing/Spacing.tsx
  EQL-Client-Project/src/components/common/spacing/Spacting.style.tsx
  EQL-Client-Project/src/components/order/BreadCrumb/BreadCrumb.style.tsx
  EQL-Client-Project/src/components/order/Coupon/Coupon.style.tsx
  EQL-Client-Project/src/components/order/Coupon/Coupon.tsx
  EQL-Client-Project/src/components/order/DeliveryInfo/DeliveryInfo.style.tsx
  EQL-Client-Project/src/components/order/DeliveryInfo/DeliveryInfo.tsx
  EQL-Client-Project/src/components/order/LightHr/LightHr.style.tsx
  EQL-Client-Project/src/components/order/LightHr/LightHr.tsx
  EQL-Client-Project/src/components/order/Notice/Notice.style.tsx
  EQL-Client-Project/src/components/order/Notice/Notice.tsx
  EQL-Client-Project/src/components/order/OrderHeader/OrderHeader.style.tsx
  EQL-Client-Project/src/components/order/OrderHeader/OrderHeader.tsx
  EQL-Client-Project/src/components/order/OrderProductInfo/OrderProductInfo.style.tsx
  EQL-Client-Project/src/components/order/OrderProductInfo/OrderProductInfo.tsx
  EQL-Client-Project/src/components/order/PaymentInfo/PaymentInfo.style.tsx
  EQL-Client-Project/src/components/order/PaymentInfo/PaymentInfo.tsx
  EQL-Client-Project/src/components/order/PaymentMethod/PaymentMethod.style.tsx
  EQL-Client-Project/src/components/order/PaymentMethod/PaymentMethod.tsx
  EQL-Client-Project/src/constants/ItemSummaries.ts
  EQL-Client-Project/src/constants/Notice.ts
  EQL-Client-Project/src/constants/OtherPaymentMethods.ts
  EQL-Client-Project/src/pages/Order/Order.style.tsx
  EQL-Client-Project/src/pages/Order/Order.tsx
Labels: feat, 재훈

#43 Feat/#39/category api
  EQL-Client-Project/.gitignore
  EQL-Client-Project/src/components/Category/CategoryProductList/CategoryProductList.style.tsx
  EQL-Client-Project/src/components/Category/CategoryProductList/CategoryProductList.tsx
Labels: 수연, API

#44 [Fix/#42] 공통 컴포넌트 - header hover
  EQL-Client-Project/src/Router.tsx
  EQL-Client-Project/src/assets/Images/0_images.ts
  EQL-Client-Project/src/components/common/LayoutComponent.tsx
  EQL-Client-Project/src/components/header/Header.style.tsx
  EQL-Client-Project/src/components/header/Header.tsx
  EQL-Client-Project/src/components/header/dropdown/DropDown.style.tsx
  EQL-Client-Project/src/components/header/dropdown/DropDown.tsx
  EQL-Client-Project/src/components/order/PaymentMethod/PaymentMethod.tsx
  EQL-Client-Project/src/constants/ProductImgs.ts
  EQL-Client-Project/src/pages/Home/Home.style.tsx
  EQL-Client-Project/src/pages/Home/Home.tsx
Labels: fix, 재훈

#47 [Feat/#30] product 페이지 api연결
  EQL-Client-Project/src/pages/Product/Left.style.tsx
  EQL-Client-Project/src/pages/Product/Left.tsx
  EQL-Client-Project/src/pages/Product/Product.tsx
  EQL-Client-Project/src/pages/Product/Right.style.tsx
  EQL-Client-Project/src/pages/Product/Right.tsx
  EQL-Client-Project/src/types/product.ts
Labels: 시연, Product, API

#48 [Feat/#9]home view
  EQL-Client-Project/package.json
  EQL-Client-Project/src/assets/Images/CarouselFirstImg.png
  EQL-Client-Project/src/assets/Images/CarouselSecondImg.png
  EQL-Client-Project/src/assets/Images/CarouselThirdImg.png
  EQL-Client-Project/src/assets/Images/ImgPost1.png
  EQL-Client-Project/src/assets/Images/ImgPost10.png
  EQL-Client-Project/src/assets/Images/ImgPost11.png
  EQL-Client-Project/src/assets/Images/ImgPost2.png
  EQL-Client-Project/src/assets/Images/ImgPost3.png
  EQL-Client-Project/src/assets/Images/ImgPost4.png
  EQL-Client-Project/src/assets/Images/ImgPost5.png
  EQL-Client-Project/src/assets/Images/ImgPost7.png
  EQL-Client-Project/src/assets/Images/ImgPost8.png
  EQL-Client-Project/src/assets/Images/ImgPost9.png
  EQL-Client-Project/src/assets/Images/ImgRec1.png
  EQL-Client-Project/src/assets/Images/ImgRec2.png
  EQL-Client-Project/src/assets/Images/ImgRec3.png
  EQL-Client-Project/src/assets/Images/ImgRec4.png
  EQL-Client-Project/src/assets/Images/ImgRec5.png
  EQL-Client-Project/src/assets/Images/ImgRec6.png
  EQL-Client-Project/src/assets/Images/ImgRec7.png
  EQL-Client-Project/src/assets/images/index.ts
  EQL-Client-Project/src/assets/svgs/0_icons.ts
  EQL-Client-Project/src/assets/svgs/IcArrowBlackRight.svg
  EQL-Client-Project/src/assets/svgs/IcBar.svg
  EQL-Client-Project/src/assets/svgs/IcNext.svg
  EQL-Client-Project/src/assets/svgs/IcPrevious.svg
  EQL-Client-Project/src/components/home/Banner/Banner.style.tsx
  EQL-Client-Project/src/components/home/Banner/Banner.tsx
  EQL-Client-Project/src/components/home/Content/ContentContainer/Content.style.tsx
  EQL-Client-Project/src/components/home/Content/ContentContainer/Content.tsx
  EQL-Client-Project/src/components/home/Content/ContentWrapper/ContentWrapper.style.tsx
  EQL-Client-Project/src/components/home/Content/ContentWrapper/ContentWrapper.tsx
  EQL-Client-Project/src/components/home/Section/SectionContainer/SectionContainer.style.tsx
  EQL-Client-Project/src/components/home/Section/SectionContainer/SectionContainer.tsx
  EQL-Client-Project/src/components/home/Section/SectionLayout/SectionLayout.style.tsx
  EQL-Client-Project/src/components/home/Section/SectionLayout/SectionLayout.tsx
  EQL-Client-Project/src/components/home/Section/SectionWrapper/SectionWrapper.style.tsx
  EQL-Client-Project/src/components/home/Section/SectionWrapper/SectionWrapper.tsx
  EQL-Client-Project/src/pages/Home/Home.style.tsx
  EQL-Client-Project/src/pages/Home/Home.tsx
  EQL-Client-Project/yarn.lock
Labels: 준민, Home
